/**
 * Inventaire des e-mails transactionnels — audit migration images (GCS/Firebase → site vitrine).
 * Tous passent par MailerService.prepareHtml() → resolveHtmlMediaUrls() sauf note contraire.
 */
export type EmailImageRisk = 'none' | 'header_logo' | 'inline' | 'hero' | 'json_ld';

export type EmailSendPoint = {
  id: string;
  service: string;
  description: string;
  transport: 'sendSimple' | 'sendAdNotificationEmail';
  logContext?: string;
  imageRisk: EmailImageRisk;
  /** Comment les images legacy sont neutralisées. */
  mitigation: string;
};

export const EMAIL_SEND_POINTS: readonly EmailSendPoint[] = [
  {
    id: 'auth-signup-verify',
    service: 'auth.service.ts',
    description: 'Code vérification inscription',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Logo en-tête via getBrandAsync → resolveEmailImageUrl (web)',
  },
  {
    id: 'auth-welcome',
    service: 'auth.service.ts',
    description: 'Bienvenue / activation compte',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Logo en-tête via wrapBodyAsync',
  },
  {
    id: 'auth-password-reset',
    service: 'auth.service.ts',
    description: 'Réinitialisation mot de passe',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Logo en-tête via wrapBodyAsync',
  },
  {
    id: 'auth-2fa',
    service: 'auth.service.ts',
    description: 'Codes 2FA / OTP',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Logo en-tête via wrapBodyAsync',
  },
  {
    id: 'login-notification',
    service: 'login-notification.service.ts',
    description: 'Alerte nouvelle connexion',
    transport: 'sendSimple',
    logContext: 'login-notification',
    imageRisk: 'header_logo',
    mitigation: 'Logo en-tête via wrapBodyAsync',
  },
  {
    id: 'order-paid-invoice',
    service: 'order-paid-invoice-email.service.ts',
    description: 'Reçu commande payée + PDF',
    transport: 'sendSimple',
    logContext: 'order-paid-invoice',
    imageRisk: 'json_ld',
    mitigation:
      'Vignettes snapshot → resolveSnapshotMediaUrls ; logo JSON-LD → resolveEmailImageUrl ; prepareHtml réécrit img + JSON-LD',
  },
  {
    id: 'order-shipped',
    service: 'order-paid-invoice-email.service.ts',
    description: 'Commande expédiée',
    transport: 'sendSimple',
    logContext: 'order-shipped',
    imageRisk: 'json_ld',
    mitigation: 'Idem order-paid-invoice',
  },
  {
    id: 'order-email-debug',
    service: 'order-paid-invoice-email.service.ts',
    description: 'Envoi debug reçu commande',
    transport: 'sendSimple',
    logContext: 'order-email-debug-*',
    imageRisk: 'json_ld',
    mitigation: 'Idem order-paid-invoice',
  },
  {
    id: 'ad-notification',
    service: 'ad-notification.service.ts',
    description: 'Campagne / bannière pub (miniatures produits)',
    transport: 'sendAdNotificationEmail',
    imageRisk: 'inline',
    mitigation:
      'Miniatures catalogue dans HTML → prepareHtml resolveAllEmailHtmlStorageUrls',
  },
  {
    id: 'gift-code-activation',
    service: 'gift-code-activation-notifier.service.ts',
    description: 'Activation code cadeau (image promo)',
    transport: 'sendAdNotificationEmail',
    logContext: 'gift-code-activation',
    imageRisk: 'inline',
    mitigation:
      'imageUrl résolu à la source (resolveEmailImageUrl) + prepareHtml filet',
  },
  {
    id: 'partner-onboarding',
    service: 'partner-onboarding-email.service.ts',
    description: 'Onboarding vendeur / livreur (hero + sections)',
    transport: 'sendSimple',
    imageRisk: 'hero',
    mitigation: 'Hero + sections → pool statique africa-meals-web (EmailAiHeroImageService)',
  },
  {
    id: 'ad-cash-grant',
    service: 'ad-cash-email.service.ts',
    description: 'Crédit Ad Cash boutique',
    transport: 'sendSimple',
    imageRisk: 'hero',
    mitigation: 'Hero → pool statique web',
  },
  {
    id: 'vendor-status',
    service: 'vendor-status-email.service.ts',
    description: 'Statut boutique / KYC / approbation',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'platform-maintenance',
    service: 'platform-maintenance-email.service.ts',
    description: 'Bascule mode maintenance',
    transport: 'sendSimple',
    logContext: 'platform-maintenance-toggle',
    imageRisk: 'hero',
    mitigation: 'Hero → resolveMaintenanceModeHeroUrl (web /images/email-heroes/)',
  },
  {
    id: 'maintenance-alert',
    service: 'maintenance-alert-notifier.service.ts',
    description: 'Alerte ops maintenance',
    transport: 'sendSimple',
    logContext: 'maintenance-alert',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'blog-newsletter',
    service: 'blog-newsletter-dispatch.service.ts',
    description: 'Newsletter article blog (image à la une)',
    transport: 'sendSimple',
    logContext: 'blog-newsletter:*',
    imageRisk: 'inline',
    mitigation:
      'featuredImageUrl résolu à l’enqueue + prepareHtml filet sur HTML fragment',
  },
  {
    id: 'food-newsletter',
    service: 'food-newsletter-delivery.service.ts',
    description: 'Newsletter recommandations (pixel ouverture API)',
    transport: 'sendSimple',
    logContext: 'food-newsletter-delivery',
    imageRisk: 'inline',
    mitigation:
      'Pixel tracking → URL API (pas GCS) ; HTML pré-enveloppé → prepareHtml réécrit si besoin',
  },
  {
    id: 'business-report',
    service: 'business-report-email.service.ts',
    description: 'Signalement (business report)',
    transport: 'sendSimple',
    logContext: 'business-report-*',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'contact-inbound',
    service: 'contact-submission.service.ts',
    description: 'Formulaire contact → support',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'contact-reply',
    service: 'contact-submission.service.ts',
    description: 'Réponse support au visiteur',
    transport: 'sendSimple',
    logContext: 'site-contact-reply',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'vendor-subscription',
    service: 'vendor-subscription-email.service.ts',
    description: 'Abonnement vendeur (facturation)',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'penalty-participant',
    service: 'penalty-participant-email.service.ts',
    description: 'Notification pénalité participant',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'refund-customer',
    service: 'refund-processing.service.ts',
    description: 'Remboursement client',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'store-status',
    service: 'store.service.ts',
    description: 'Statut restaurant mis à jour',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'store-team-invite',
    service: 'store.service.ts',
    description: 'Invitation équipe boutique',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'store-delivery-driver-invite',
    service: 'store-delivery-drivers.service.ts',
    description: 'Invitation livreur boutique',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'store-delivery-driver-left',
    service: 'store-delivery-drivers.service.ts',
    description: 'Livreur quitte flotte restaurant partenaire',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'delivery-agent',
    service: 'delivery-agent.service.ts',
    description: 'Candidature / statut livreur plateforme',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'vendor-notification',
    service: 'vendor-notification-dispatch.service.ts',
    description: 'Alertes commandes vendeur',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'vendor-stripe-billing',
    service: 'vendor-notification-stripe-billing.service.ts',
    description: 'Facture SMS Stripe vendeur',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'admin-ops-report',
    service: 'admin-ops-reports.service.ts',
    description: 'Rapport ops admin (Excel joint)',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'admin-alert',
    service: 'admin-alert-email.service.ts',
    description: 'Campagne alerte administrateur',
    transport: 'sendSimple',
    logContext: 'admin-alert:*',
    imageRisk: 'header_logo',
    mitigation: 'Texte seul + logo en-tête',
  },
  {
    id: 'mailer-test',
    service: 'mailer-test-email.controller.ts',
    description: 'E-mail de test SMTP',
    transport: 'sendSimple',
    imageRisk: 'header_logo',
    mitigation: 'Logo en-tête via wrapBodyAsync',
  },
  {
    id: 'test-email-media',
    service: 'scripts/test-email-media-images.ts',
    description: 'Diagnostic migration images',
    transport: 'sendSimple',
    logContext: 'test_email_media_images',
    imageRisk: 'hero',
    mitigation: 'resolveEmailImageUrl + hero pool web',
  },
] as const;
